---
- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Install EPEL repo.
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      state: present
  - name: Import EPEL GPG key.
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
      state: present
  - name: "Installing Docker Prerequisite packages"
    yum:
      state: latest
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python-pip
  - name: "Install Docker SDK for Python"
    shell: pip install docker
  - name: "Configuring docker-ce repo"
    get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
  - name: " Installing Docker latest version"
    yum:
      name: docker-ce
      state: present
  - name: " Starting and Enabling Docker service"
    service:
      name: docker
      state: started
      enabled: yes
